package edu.isistan.stroulia.loaders;

public enum PrimitiveType {
	COMMANDSWAPCOLORSFLAGSCONSTANTS, COMMANDSMOOTHFLAGSCONSTANTS, COMMANDROTATEFLAGSCONSTANTS, COMMANDLINEREMOVEFLAGSCONSTANTS, COMMANDINVERTEDTEXTFLAGSCONSTANTS, COMMANDHOLEPUNCHREMOVEFLAGSCONSTANTS, COMMANDDOTREMOVEFLAGSCONSTANTS, COMMANDBORDERREMOVEFLAGSCONSTANTS, COMMANDBORDERFLAGSCONSTANTS, UNSIGNEDLONG, UNSIGNEDINT, POSITIVEINTEGERORALL, NONNEGATIVEINTEGER, NAME, ADJUSTMENTMETHODS, QNAME, NCNAME, TIME, UNSIGNEDSHORT, NMTOKEN, ANYURI, BASE64BINARY, BYTE, SHORT, INT, INTEGER, LONG, FLOAT, DOUBLE, DECIMAL, CHAR, STRING, BOOLEAN, DATE, DATETIME
}
