package com.isistan.loaders;

public enum DataSetProperty {
	RESOURCES_PATH, INPUT_PATH, QUERY_PATH, RESULTS_PATH, HITLIST_FILENAMES, HITLIST_PATH, HITLIST_RESULTS_FILENAME, RESULTS_FILENAME, ORIGINALS_PATH
}
