package com.isistan.loaders;

public enum PrimitiveType {
	NCNAME, TIME, UNSIGNEDSHORT, NMTOKEN, ANYURI, BASE64BINARY, BYTE, SHORT, INT, INTEGER, LONG, FLOAT, DOUBLE, DECIMAL, CHAR, STRING, BOOLEAN, DATE, DATETIME
}
